version: '3.8'

services:
  application:
    image: events-image:latest
    container_name: project_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://events_db:5432/events_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'
    networks:
      - app_network
    depends_on:
      - events_db

  events_db:
    image: 'postgres:15'
    container_name: events_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=events_db

    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
