server:
  port: 8080

spring:
  application:
    name: pet
  datasource:
    url: jdbc:postgresql://localhost:5432/events_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    cleanOnValidationError: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-name: ${OAUTH2_CLIENT_NAME}

jwt:
  secret-key: ${APP_SECRET_KEY}
  access-lifetime: 15m
  refresh-lifetime: 7d

logging:
  level:
    org.springframework.security: trace
    org.apache.http: DEBUG
    root: INFO
    com.example: DEBUG

